SELECT *
FROM REGIONVIEW;

SELECT *
FROM DEPARTMENTVIEW;

SELECT DEPARTMENTID, DEPARTMENTNAME, DELCHECK 
FROM DEPARTMENTVIEW WHERE DEPARTMENTNID=1;

--DEPARTMENTID

SELECT DEPARTMENTID, DEPARTMENTNAME, DELCHECK 
FROM DEPARTMENTVIEW WHERE DEPARTMENTID=1;

SELECT COUNT(*) AS COUNT FROM DEPARTMENT WHERE DEPARTMENTNAME = '도서부';

SELECT *
FROM POSITIONVIEW;

SELECT POSITIONID, POSITIONNAME, MINBASICPAY
FROM POSITIONVIEW
WHERE POSITIONID=1;
--==>> 한 줄 수정
SELECT POSITIONID, POSITIONNAME, MINBASICPAY FROM POSITIONVIEW WHERE POSITIONID=1
;


SELECT COUNT(*) AS COUNT
FROM POSITION
WHERE POSITIONNAME = '사원';
--==>> 한 줄 수정
SELECT COUNT(*) AS COUNT FROM POSITION WHERE POSITIONNAME = '사원'
;


