SELECT USER
FROM DUAL;

-- DB설계 취합

-- 1. 계정테이블
CREATE TABLE ACCOUNT
( AC_NO     NUMBER
, CONSTRAINT AC_NO_PK PRIMARY KEY(AC_NO)
);

-- 2. 관리자 테이블
CREATE TABLE ADMIN
( AD_ID     VARCHAR2(30)    
, AD_PW     VARCHAR2(30)    NOT NULL
, CONSTRAINT AD_ID_PK PRIMARY KEY(AD_ID)
);

-- 1순위
-- 3. 질문 분류 테이블
CREATE TABLE FAQ_SORT
( QS_NO     NUMBER
, NAME      VARCHAR2(20)   
, CONSTRAINT QS_NO_PK   PRIMARY KEY(QS_NO)
);

-- 4. 공지사항 분류 테이블
CREATE TABLE NOTICE_SORT
( NOS_NO    NUMBER
, NAME      VARCHAR2(20)
, CONSTRAINT NOS_NO_PK  PRIMARY KEY(NOS_NO)
);

-- 5. 신고사유 테이블
CREATE TABLE REPORT_WHY
( WHY_NO    NUMBER
, TITLE     VARCHAR2(200)
, CONSTRAINT WHY_NO_PK PRIMARY KEY(WHY_NO)
);

-- 6. 신고 처리상태 테이블
CREATE TABLE REPORT_STATUS
( STATUS_NO     NUMBER
, STATUSNAME    VARCHAR2(20)
, AD_ID         VARCHAR2(30)
, CONSTRAINT STATUS_NO_PK PRIMARY KEY(STATUS_NO)
, CONSTRAINT AD_ID_FK FOREIGN KEY(AD_ID)
            REFERENCES ADMIN(AD_ID)
);

ALTER TABLE REPORT_STATUS DROP COLUMN AD_ID;
SELECT *
FROM REPORT_STATUS;

-- 7. 서울시 구 (1순위)
CREATE TABLE GU
( GU_NO NUMBER
, GUNAME VARCHAR2(30) NOT NULL
,CONSTRAINT GU_GU_NO_PK PRIMARY KEY (GU_NO)
);

-- 8. 점수 (1순위)
CREATE TABLE SCORE
( SCORENO NUMBER
, SCORENAME NUMBER(1)
,CONSTRAINT SCORE_SCORENO_PK PRIMARY KEY(SCORENO)
);

-- 9. 개인정보
CREATE TABLE PERSONAL
( PE_ID         VARCHAR2(30)    NOT NULL
, AC_NO         NUMBER          NOT NULL
, NAME          VARCHAR2(30)    NOT NULL
, TEL           VARCHAR2(30)    NOT NULL
, NICKNAME      VARCHAR2(30)    NOT NULL
, PW            VARCHAR2(30)    NOT NULL
, EMAIL         VARCHAR2(30)    NOT NULL
, ROADADDR      VARCHAR2(50)    NOT NULL
, DETAILADDR    VARCHAR2(100)   NOT NULL
, PROFILE       VARCHAR2(500)
, PEDATE        DATE            NOT NULL
, CONSTRAINT PERSONAL_PE_ID_PK PRIMARY KEY(PE_ID)
, CONSTRAINT PERSONAL_AC_NO_FK FOREIGN KEY(AC_NO)
             REFERENCES ACCOUNT(AC_NO)
, CONSTRAINT PERSONAL_TEL_UK UNIQUE(TEL)
, CONSTRAINT PERSONAL_NICKNAME_UK UNIQUE(NICKNAME)
);

-- 10. 거주여부
CREATE TABLE RESIDENCE      -- 거주여부 (1순위)
( RES_NO        NUMBER          NOT NULL
, RESIDENCENAME VARCHAR2(10)    NOT NULL
);

ALTER TABLE RESIDENCE ADD CONSTRAINT RES_NO_PK PRIMARY KEY(RES_NO);

-- 11. 탈퇴사유
CREATE TABLE WITHDRAWAL_WHY
( WIR_NO NUMBER
, WHY VARCHAR2(50)
, CONSTRAINT WITHDRAWAL_WHY_NO PRIMARY KEY(WIR_NO)
);


--2순위
-- 12.서울시 동 (2순위)
CREATE TABLE DONG
( DONG_NO NUMBER
, GU_NO NUMBER
, DONGNAME VARCHAR2(30) NOT NULL
,CONSTRAINT DONG_DONG_NO_PK PRIMARY KEY(DONG_NO)
,CONSTRAINT DONG_GU_NO_FK FOREIGN KEY(GU_NO)
REFERENCES GU (GU_NO)
);

-- 13. 탈퇴회원 테이블
CREATE TABLE WITHDRAWAL
( WI_NO     NUMBER
, AC_NO     NUMBER
, WIR_NO    NUMBER
, COMMENTS   VARCHAR2(300)
, WIDATE    DATE
, ID        VARCHAR2(30)
, NAME      VARCHAR2(30)
, TEL       VARCHAR2(30)
, CONSTRAINT WI_NO_PK PRIMARY KEY(WI_NO)
, CONSTRAINT AC_NO_FK   FOREIGN KEY(AC_NO)
            REFERENCES ACCOUNT(AC_NO)
, CONSTRAINT WIR_NO_FK  FOREIGN KEY(WIR_NO)
            REFERENCES WITHDRAWAL_WHY(WIR_NO)
);
--==> Table WITHDRAWAL이(가) 생성되었습니다.
DROP TABLE WITHDRAWAL;

-- 14. 공지사항
CREATE TABLE NOTICE
( NO_NO     NUMBER          NOT NULL
, AD_ID     VARCHAR2(30)    NOT NULL
, NOS_NO    NUMBER          NOT NULL
, TITLE     VARCHAR2(100)
, CONTENT   VARCHAR2(500)
, NODATE    DATE
, CONSTRAINT NOTICE_NO_NO_PK PRIMARY KEY(NO_NO)
, CONSTRAINT NOTICE_AD_ID_FK FOREIGN KEY(AD_ID)
             REFERENCES ADMIN(AD_ID)
, CONSTRAINT NOTICE_NOS_NO_FK FOREIGN KEY(NOS_NO)
             REFERENCES NOTICE_SORT(NOS_NO)
);

-- 15. 자주 묻는 질문
CREATE TABLE FAQ
( FAQ_NO    NUMBER          NOT NULL
, AD_ID     VARCHAR2(30)    NOT NULL
, QS_NO     NUMBER          NOT NULL
, TITLE     VARCHAR2(100)
, CONTENT   VARCHAR2(500)
, CONSTRAINT FAQ_NO_PK PRIMARY KEY(FAQ_NO)
, CONSTRAINT FAQ_AD_ID_FK FOREIGN KEY(AD_ID)
             REFERENCES ADMIN(AD_ID)
, CONSTRAINT FAQ_QS_NO_FK FOREIGN KEY(QS_NO)
             REFERENCES FAQ_SORT(QS_NO)
);

-- 16. 서비스 소개 게시판
CREATE TABLE INTRODUCTION
( IN_NO     NUMBER          NOT NULL
, AD_ID     VARCHAR2(30)    NOT NULL
, CONTENT   VARCHAR2(500)
, CONSTRAINT INTRO_IN_NO_PK PRIMARY KEY(IN_NO)
, CONSTRAINT INTRO_AD_ID_FK FOREIGN KEY(AD_ID)
             REFERENCES ADMIN(AD_ID)
);

-- 17. 체크리스트
CREATE TABLE CHECKLIST      -- 체크리스트 (2순위)
( CHECK_NO  NUMBER          NOT NULL
, AC_NO     NUMBER          NOT NULL
, RES_NO    NUMBER          NOT NULL
, CHECKDATE DATE
, TITLE     VARCHAR2(50)    NOT NULL
, ROADADDR  VARCHAR2(100)   NOT NULL
, DONG_NO   NUMBER          NOT NULL
, WIDO      VARCHAR2(30)
, GYEONGDO  VARCHAR2(30)
, CONSTRAINT CHECKLIST_NO_PK PRIMARY KEY(CHECK_NO)
, CONSTRAINT CHECKLIST_ACNO_FK FOREIGN KEY(AC_NO)
            REFERENCES ACCOUNT(AC_NO)
, CONSTRAINT CHECKLIST_RESNO_FK FOREIGN KEY(RES_NO)
            REFERENCES RESIDENCE(RES_NO)
, CONSTRAINT CHECKLIST_DONGNO_FK FOREIGN KEY(DONG_NO)
            REFERENCES DONG(DONG_NO)
);


--3순위
-- 18. 신고(체크리스트) 테이블
CREATE TABLE REPORT_CHECK
( RPCHECK_NO    NUMBER
, REPORTDATE    DATE
, CHECK_NO      NUMBER
, AC_NO         NUMBER        
, WHY_NO        NUMBER     
, WHY           VARCHAR2(500)
, STATUS_NO     NUMBER
, CONSTRAINT RPCHECK_NO_PK  PRIMARY KEY(RPCHECK_NO)
, CONSTRAINT RPCHECK_NO_FK    FOREIGN KEY(CHECK_NO)
                REFERENCES CHECKLIST(CHECK_NO)
, CONSTRAINT RPCHECK_AC_NO_FK   FOREIGN KEY(AC_NO)
                REFERENCES ACCOUNT(AC_NO)
, CONSTRAINT RPCHECK_WHY_NO_FK  FOREIGN KEY(WHY_NO)
                REFERENCES REPORT_WHY(WHY_NO)
, CONSTRAINT RPCHECK_STATUS_NO_FK   FOREIGN KEY(STATUS_NO)
                REFERENCES REPORT_STATUS(STATUS_NO)
);

ALTER TABLE REPORT_CHECK ADD AD_ID VARCHAR2(30);
ALTER TABLE REPORT_CHECK ADD CONFIRMDATE DATE;

SELECT * FROM REPORT_CHECK;

ALTER TABLE REPORT_CHECK ADD CONSTRAINT RPCHECK_AD_ID_FK FOREIGN KEY(AD_ID) REFERENCES ADMIN(AD_ID);

-- 19. 코멘트
CREATE TABLE CONTENT
( CHECK_NO NUMBER
, GOOD VARCHAR2(300)
, BAD VARCHAR2(300)
, ETC VARCHAR2(300)
,CONSTRAINT CONTENT_CHECK_NO_PK PRIMARY KEY(CHECK_NO)
,CONSTRAINT CONTENT_CHECK_NO_FK FOREIGN KEY(CHECK_NO)
REFERENCES CHECKLIST (CHECK_NO)
);

-- 20. 비밀코멘트 (3순위)
CREATE TABLE SECRET_CONTENT
( CHECK_NO NUMBER
, COMMENTS VARCHAR2(300)
,CONSTRAINT SECRET_CONTENT_CHECK_NO_PK PRIMARY KEY(CHECK_NO)
,CONSTRAINT SECRET_CONTENT_CHECK_NO_FK FOREIGN KEY(CHECK_NO)
REFERENCES CHECKLIST (CHECK_NO)
);

-- 21. 생활편의시설 (3순위)
CREATE TABLE CONVENIENCE
( CHECK_NO NUMBER
, MART NUMBER(1)
, LAUNDRY NUMBER(1)
, HOSPITAL NUMBER(1)
, FOOD NUMBER(1)
, CULTURE NUMBER(1)
, PARK NUMBER(1)
, COMMENTS VARCHAR2(300)
,CONSTRAINT CONVENIENCE_CHECK_NO_PK PRIMARY KEY(CHECK_NO)
,CONSTRAINT CONVENIENCE_CHECK_NO_FK FOREIGN KEY(CHECK_NO)
REFERENCES CHECKLIST (CHECK_NO)
);

-- 22. 추가항목(시간 평가) (3순위)
CREATE TABLE PLUS_TIME
( PTIME_NO NUMBER
, CHECK_NO NUMBER
, TITLE VARCHAR2(20)
, COMMENTS VARCHAR2(300)
, TIME NUMBER(3)
,CONSTRAINT PLUS_TIME_PTIME_NO_PK PRIMARY KEY(PTIME_NO)
,CONSTRAINT PLUS_TIME_CHECK_NO_FK FOREIGN KEY(CHECK_NO)
REFERENCES CHECKLIST (CHECK_NO)
);

-- 23. 추가항목(점수 평가) (3순위)
CREATE TABLE PLUS_SCORE
( PSCORE_NO NUMBER
, CHECK_NO NUMBER
, TITLE VARCHAR2(20)
, COMMENTS VARCHAR2(300)
, SCORENO NUMBER
,CONSTRAINT PLUS_SCORE_PSCORE_NO_PK PRIMARY KEY(PSCORE_NO)
,CONSTRAINT PLUS_SCORE_CHECK_NO_FK FOREIGN KEY(CHECK_NO)
REFERENCES CHECKLIST (CHECK_NO)
);

ALTER TABLE PLUS_SCORE ADD CONSTRAINT PLUS_SCORE_SCORENO_FK FOREIGN KEY(SCORENO) REFERENCES SCORE(SCORENO);

-- 24. 교통혼잡도 (3순위)
CREATE TABLE HONJAP
( CHECK_NO NUMBER
, COMMENTS VARCHAR2(300)
, SCORENO NUMBER
,CONSTRAINT HONJAP_CHECK_NO_PK PRIMARY KEY(CHECK_NO)
,CONSTRAINT HONJAP_CHECK_NO_FK FOREIGN KEY(CHECK_NO)
REFERENCES CHECKLIST (CHECK_NO)
);

-- 25. 대중교통 (3순위)
CREATE TABLE TRANSPORT
( CHECK_NO NUMBER
, COMMENTS VARCHAR2(300)
, SCORENO NUMBER NOT NULL
,CONSTRAINT TRANSPORT_CHECK_NO_PK PRIMARY KEY(CHECK_NO)
,CONSTRAINT TRANSPORT_CHECK_NO_FK FOREIGN KEY(CHECK_NO)
REFERENCES CHECKLIST (CHECK_NO)
);

-- 26. 치안
CREATE TABLE SECURITY
( CHECK_NO      NUMBER          NOT NULL
, COMMENTS       VARCHAR2(300)
, SCORENO       NUMBER          NOT NULL
, CONSTRAINT SECURITY_CHECK_NO_PK PRIMARY KEY(CHECK_NO)
, CONSTRAINT SECURITY_CHECK_NO_FK FOREIGN KEY(CHECK_NO)
             REFERENCES CHECKLIST(CHECK_NO)
, CONSTRAINT SECURITY_SCORENO_FK FOREIGN KEY(SCORENO)
             REFERENCES SCORE(SCORENO)
);

-- 27. 월세
CREATE TABLE WOLSE          -- 월세 (3순위)
( CHECK_NO      NUMBER  NOT NULL
, MWOLSE        NUMBER
, DEPOSIT       NUMBER
, CONSTRAINT WOLSE_CHECKNO_PK PRIMARY KEY(CHECK_NO)
, CONSTRAINT WOLSE_CHECKNO_FK FOREIGN KEY(CHECK_NO)
            REFERENCES CHECKLIST(CHECK_NO)
);

-- 28. 전세
CREATE TABLE JEONSE         -- 전세 (3순위)
( CHECK_NO      NUMBER  NOT NULL
, MJEONSE       NUMBER
, CONSTRAINT JEONSE_CHECKNO_PK PRIMARY KEY(CHECK_NO)
, CONSTRAINT JEONSE_CHECKNO_FK FOREIGN KEY(CHECK_NO)
            REFERENCES CHECKLIST(CHECK_NO)
);

-- 29. 매매
CREATE TABLE MAEMAE         -- 매매 (3순위)
( CHECK_NO      NUMBER  NOT NULL
, MMAEMAE       NUMBER
, CONSTRAINT MAEMAE_CHECKNO_PK PRIMARY KEY(CHECK_NO)
, CONSTRAINT MAEMAE_CHECKNO_FK FOREIGN KEY(CHECK_NO)
            REFERENCES CHECKLIST(CHECK_NO)
);

-- 30. 나의 출근시간
CREATE TABLE GOING          -- 나의 출근시간 (3순위)
( CHECK_NO      NUMBER  NOT NULL
, PLACE         VARCHAR2(30)
, TIME          NUMBER(3)
, CONSTRAINT GOING_CHECKNO_PK PRIMARY KEY(CHECK_NO)
, CONSTRAINT GOING_CHECKNO_FK FOREIGN KEY(CHECK_NO)
            REFERENCES CHECKLIST(CHECK_NO)
);

-- 31. 반려동물
CREATE TABLE PET            -- 반려동물 (3순위)
( CHECK_NO      NUMBER  NOT NULL
, COMMENTS      VARCHAR2(300)
, SCORENO       NUMBER  NOT NULL
, CONSTRAINT PET_CHECKNO_PK PRIMARY KEY(CHECK_NO)
, CONSTRAINT PET_CHECKNO_FK FOREIGN KEY(CHECK_NO)
            REFERENCES CHECKLIST(CHECK_NO)
, CONSTRAINT PET_SCORENO_FK FOREIGN KEY(SCORENO)
            REFERENCES SCORE(SCORENO)
);


--4순위
-- 32. 북마크 스티커
CREATE TABLE CHECKSTICKER
( CSTICKER_NO   NUMBER
, AC_NO         NUMBER          NOT NULL
, CONTENT       VARCHAR2(30)
, CONSTRAINT CHECKSTICKER_NO_PK PRIMARY KEY(CSTICKER_NO)
, CONSTRAINT CHECKSTICKER_AC_NO_FK FOREIGN KEY(AC_NO)
REFERENCES ACCOUNT(AC_NO)
);

-- 33. 북마크 지역정보
CREATE TABLE LOCAL_BOOKMARK
( LO_B_NO   NUMBER
, DONG_NO   NUMBER  NOT NULL
, AC_NO     NUMBER  NOT NULL
, MARKDATE  DATE    NOT NULL
, CONSTRAINT LOCALMARK_LO_B_NO_PK PRIMARY KEY(LO_B_NO)
, CONSTRAINT LOCALMARK_DONG_NO_FK FOREIGN KEY(DONG_NO)
REFERENCES DONG(DONG_NO)
, CONSTRAINT LOCALMARK_AC_NO_FK FOREIGN KEY(AC_NO)
REFERENCES ACCOUNT(AC_NO)
, CONSTRAINT LOCALMARK_DONGAC_UK UNIQUE(DONG_NO, AC_NO)
);

-- 34. 북마크 체크리스트
CREATE TABLE CHECK_BOOKMARK
( CH_B_NO   NUMBER
, CHECK_NO  NUMBER          NOT NULL
, TITLE     VARCHAR2(30)
, AC_NO     NUMBER          NOT NULL
, MARKDATE  DATE            NOT NULL
, CONSTRAINT CBOOKMARK_CH_B_NO_FK PRIMARY KEY(CH_B_NO)
, CONSTRAINT CBOOKMARK_AC_NO_FK FOREIGN KEY(AC_NO)
REFERENCES ACCOUNT(AC_NO)
, CONSTRAINT CBOOKMARK_CHECK_NO_FK FOREIGN KEY(CHECK_NO)
REFERENCES CHECKLIST(CHECK_NO)
, CONSTRAINT CBOOKMARK_CHECKAC_UK UNIQUE(CHECK_NO, AC_NO)
);

--5순위
-- 35. 지역정보 부착 스티커
CREATE TABLE LOCALTAG
( LO_TAG_NO NUMBER
, LO_B_NO   NUMBER  NOT NULL
, STIKER_NO NUMBER  NOT NULL
, CONSTRAINT LOCALTAG_LO_TAG_NO_PK PRIMARY KEY(LO_TAG_NO)
, CONSTRAINT LOCALTAG_LO_B_NO_FK FOREIGN KEY(LO_B_NO)
            REFERENCES LOCAL_BOOKMARK(LO_B_NO)
);

ALTER TABLE LOCALTAG RENAME COLUMN STIKER_NO TO CSTICKER_NO;

-- 36. 체크리스트 부착 스티커
CREATE TABLE CHECKTAG
( CH_TAG_NO     NUMBER
, CH_B_NO       NUMBER  NOT NULL
, CSTICKER_NO   NUMBER  NOT NULL
, CONSTRAINT CHECKTAG_NO_PK PRIMARY KEY(CH_TAG_NO)
, CONSTRAINT CHECKTAG_CH_B_NO_FK FOREIGN KEY(CH_B_NO)
REFERENCES CHECK_BOOKMARK(CH_B_NO)
, CONSTRAINT CHECKTAG_STICKER_NO_FK FOREIGN KEY(CSTICKER_NO)
REFERENCES CHECKSTICKER(CSTICKER_NO)
);



--------------------------------------------------------------------------------------------------------------------------

-- 공동구매 DB설계

-- ■■■1순위■■■

--테이블명
CREATE TABLE OBJECTION_STATE (
   OBJSTAT_NO   NUMBER   NOT NULL,
   STATENAME   DATE   NULL,
   AD_ID   VARCHAR2(30)   NOT NULL
);

ALTER TABLE OBJECTION_STATE ADD CONSTRAINT PK_OBJECTION_STATE PRIMARY KEY (
   OBJSTAT_NO
);

--테이블명
CREATE TABLE OBJECTIONWHY (
   OBJWHY_NO   NUMBER   NOT NULL,
   WHY   VARCHAR2(300)   NULL
);

ALTER TABLE OBJECTIONWHY ADD CONSTRAINT PK_OBJECTIONWHY PRIMARY KEY (
   OBJWHY_NO
);


--테이블명
CREATE TABLE MANNERSTICKER (
   MSTICKER_NO   NUMBER   NOT NULL,
   NAME   VARCHAR2(30)   NULL
);

ALTER TABLE MANNERSTICKER ADD CONSTRAINT PK_MANNERSTICKER PRIMARY KEY (
   MSTICKER_NO
);

--테이블명
CREATE TABLE REVIEWGRADE (
   REGRADE_NO   NUMBER   NOT NULL,
   NAME   VARCHAR2(30)   NULL
);

ALTER TABLE REVIEWGRADE ADD CONSTRAINT PK_REVIEWGRADE PRIMARY KEY (
   REGRADE_NO
);

--테이블명
CREATE TABLE REFUNDWHY (
   REFUNDWHY_NO   NUMBER   NOT NULL,
   WHY   VARCHAR2(20)   NULL
);

ALTER TABLE REFUNDWHY ADD CONSTRAINT PK_REFUNDWHY PRIMARY KEY (
   REFUNDWHY_NO
);

--테이블명
CREATE TABLE EXPRESS_BUYER (
   EXBUYER_NO   NUMBER   NOT NULL,
   EXPRESS   VARCHAR2(20)   NULL
);

ALTER TABLE EXPRESS_BUYER ADD CONSTRAINT PK_EXPRESS_BUYER PRIMARY KEY (
   EXBUYER_NO
);

--테이블명
CREATE TABLE EXPRESS_SELLER (
   EXSELLER_NO   NUMBER   NOT NULL,
   EXPRESS   VARCHAR2(20)   NULL
);

ALTER TABLE EXPRESS_SELLER ADD CONSTRAINT PK_EXPRESS_SELLER PRIMARY KEY (
   EXSELLER_NO
);

--테이블명
CREATE TABLE GUIN_STATUSTYPE (
   GST_NO   NUMBER   NOT NULL,
   STATUSTYPE   VARCHAR2(20)   NULL
);

ALTER TABLE GUIN_STATUSTYPE ADD CONSTRAINT PK_GUIN_STATUSTYPE PRIMARY KEY (
   GST_NO
);

--테이블명
CREATE TABLE MENU (
   MENU_NO   NUMBER   NOT NULL,
   MENUNAME   VARCHAR2(20)   NULL
);

ALTER TABLE MENU ADD CONSTRAINT PK_MENU PRIMARY KEY (
   MENU_NO
);

--테이블명
CREATE TABLE GUIN_MEMBER (
   GUMEM_NO   NUMBER   NOT NULL,
   MEMBERNAME   VARCHAR2(10)   NULL
);

ALTER TABLE GUIN_MEMBER ADD CONSTRAINT PK_GUIN_MEMBER PRIMARY KEY (
   GUMEM_NO
);

--테이블명
CREATE TABLE GRADE (
   GRADE_NO   NUMBER   NOT NULL,
   NAME   VARCHAR2(20)   NULL,
   SCORE   NUMBER(2)   NULL
);

ALTER TABLE GRADE ADD CONSTRAINT PK_GRADE PRIMARY KEY (
   GRADE_NO
);

--테이블명
CREATE TABLE INGPERIOD (
   PERIOD_NO   NUMBER   NOT NULL,
   PERIODNAME   VARCHAR2(10)   NULL,
   PERIOD   NUMBER(3)   NULL
);

ALTER TABLE INGPERIOD ADD CONSTRAINT PK_INGPERIOD PRIMARY KEY (
   PERIOD_NO
);


--■■■2순위■■■
--테이블명
CREATE TABLE GUIN (
   GUIN_NO   NUMBER   NOT NULL,
   AC_NO   NUMBER   NOT NULL,
   MENU_NO   NUMBER   NOT NULL,
   SHOP   VARCHAR2(30)   NULL,
   FOOD   VARCHAR2(30)   NULL,
   PRICE   NUMBER   NULL,
   DELIVERY   NUMBER   NULL,
   PERIOD   NUMBER   NULL,
   ROADADDR   VARCHAR2(50)   NULL,
   DETAILADDR   VARCHAR2(100)   NULL,
   GRADE_NO   NUMBER   NOT NULL,
   COMMENTS   VARCHAR(500)   NOT NULL,
   GUMEM_NO   NUMBER   NOT NULL
);

ALTER TABLE GUIN ADD CONSTRAINT PK_GUIN PRIMARY KEY (
   GUIN_NO
);



--■■■3순위■■■
--테이블명
CREATE TABLE PAY (
   PAY_NO   NUMBER   NOT NULL,
   PAYNUMBER   VARCHAR2(30)   NULL,
   PAYMONEY   NUMBER   NULL,
   PAYDATE   DATE   NULL,
   GUIN_NO   NUMBER   NOT NULL
);

ALTER TABLE PAY ADD CONSTRAINT PK_PAY PRIMARY KEY (
   PAY_NO
);

--테이블명
CREATE TABLE GUIN_STATUS (
   GUINSTATUS_NO   NUMBER   NOT NULL,
   GUIN_NO   NUMBER   NOT NULL,
   GST_NO   NUMBER   NOT NULL,
   STDATE   DATE   NULL
);

ALTER TABLE GUIN_STATUS ADD CONSTRAINT PK_GUIN_STATUS PRIMARY KEY (
   GUINSTATUS_NO
);

--테이블명
CREATE TABLE ING (
   GUIN_NO   NUMBER   NOT NULL,
   ARRIVE   NUMBER   NULL,
   PHOTO   VARCHAR2(500)   NULL,
   PAYMENTTIME   DATE   NULL
);

ALTER TABLE ING ADD CONSTRAINT PK_ING PRIMARY KEY (
   GUIN_NO
);

--테이블명
CREATE TABLE GUIN_REPLY (
   GUIN_REPLY_NO   NUMBER   NOT NULL,
   AC_NO   NUMBER   NOT NULL,
   GUIN_NO   NUMBER   NOT NULL,
   REPLYDATE   DATE   NULL,
   REPLY   VARCHAR(500)   NULL,
   REREPLY_NO   NUMBER   NOT NULL
);

ALTER TABLE GUIN_REPLY ADD CONSTRAINT PK_GUIN_REPLY PRIMARY KEY (
   GUIN_REPLY_NO
);

--테이블명
CREATE TABLE REPORT_GUIN (
   RPGU_NO   NUMBER   NOT NULL,
   REPORTDATE   DATE   NULL,
   GUIN_NO   NUMBER   NOT NULL,
   AC_NO   NUMBER   NOT NULL,
   REASON_NO   NUMBER   NOT NULL,
   WHY   VARCHAR2(500)   NULL,
   STATUS_NO   NUMBER   NOT NULL
);

ALTER TABLE REPORT_GUIN ADD CONSTRAINT PK_REPORT_GUIN PRIMARY KEY (
   RPGU_NO
);


--■■■4순위■■■
--테이블명
CREATE TABLE REFUND (
   REFUND_NO   NUMBER   NOT NULL,
   REFUNDDATE   DATE   NULL,
   PAY_NO   NUMBER   NOT NULL,
   REASON_NO   NUMBER   NOT NULL
);

ALTER TABLE REFUND ADD CONSTRAINT PK_REFUND PRIMARY KEY (
   REFUND_NO
);

--테이블명
CREATE TABLE BUYER (
   BUYER_NO   NUMBER   NOT NULL,
   GUIN_NO   NUMBER   NOT NULL,
   AC_NO   NUMBER   NOT NULL,
   BUYERDATE   DATE   NOT NULL,
   PAY_NO   NUMBER   NOT NULL
);

ALTER TABLE BUYER ADD CONSTRAINT PK_BUYER PRIMARY KEY (
   BUYER_NO
);

--테이블명  
--GUIN_REPLY 테이블 참조댓글 고유번호 외래키 지정
ALTER TABLE GUIN_REPLY ADD CONSTRAINT FK_REREPLY_NO FOREIGN KEY(REREPLY_NO)
       REFERENCES GUIN_REPLY(GUIN_REPLY_NO);



--테이블명
CREATE TABLE REPORT_GUINREPLY (
   RPGUREPLY_NO   NUMBER   NOT NULL,
   REPORTDATE   DATE   NULL,
   REPLY_NO   NUMBER   NOT NULL,
   AC_NO   NUMBER   NOT NULL,
   REASON_NO   NUMBER   NOT NULL,
   WHY   VARCHAR2(500)   NULL,
   STATUS_NO   NUMBER   NOT NULL
);

ALTER TABLE REPORT_GUINREPLY ADD CONSTRAINT PK_REPORT_GUINREPLY PRIMARY KEY (
   RPGUREPLY_NO
);



--■■■5순위■■■
--테이블명
CREATE TABLE OBJECTION (
   OBJECTION_NO   NUMBER   NOT NULL,
   BUYER_NO   NUMBER   NOT NULL,
   OBJSTAT_NO   NUMBER   NOT NULL,
   OBJTYPE_NO   NUMBER   NOT NULL,
   WHY   VARCHAR2(300)   NULL,
   PHOTO   VARCHAR2(500)   NULL,
   SINDATE   DATE   NULL
);

ALTER TABLE OBJECTION ADD CONSTRAINT PK_OBJECTION PRIMARY KEY (
   OBJECTION_NO
);

--테이블명
CREATE TABLE REVIEW (
   REVIEW_NO   NUMBER   NOT NULL,
   REGRADE_NO   NUMBER   NOT NULL,
   BUYER_NO   NUMBER   NOT NULL,
   REVIEWDATE   DATE   NULL,
   COMMENTS   VARCHAR2(300)   NULL
);

ALTER TABLE REVIEW ADD CONSTRAINT PK_REVIEW PRIMARY KEY (
   REVIEW_NO
);

--테이블명
CREATE TABLE BUYER_ACTION (
   BUYACT_NO   NUMBER   NOT NULL,
   BUYER_NO   NUMBER   NOT NULL,
   EXBUYER_NO   NUMBER   NOT NULL,
   ACTDATE   DATE   NULL
);

ALTER TABLE BUYER_ACTION ADD CONSTRAINT PK_BUYER_ACTION PRIMARY KEY (
   BUYACT_NO
);

--테이블명
CREATE TABLE SELLER_ACTION (
   SELACT_NO   NUMBER   NOT NULL,
   BUYER_NO   NUMBER   NOT NULL,
   EXSELLER_NO   NUMBER   NOT NULL,
   ACTDATE   DATE   NULL
);

ALTER TABLE SELLER_ACTION ADD CONSTRAINT PK_SELLER_ACTION PRIMARY KEY (
   SELACT_NO
);

--테이블명
CREATE TABLE ING_REPLY (
   ING_REPLY_NO   NUMBER   NOT NULL,
   BUYER_NO   NUMBER   NOT NULL,
   REPLYDATE   DATE   NULL,
   REPLY   VARCHAR(500)   NULL,
   REREPLY_NO   NUMBER   NOT NULL
);


ALTER TABLE ING_REPLY ADD CONSTRAINT PK_ING_REPLY PRIMARY KEY (
   ING_REPLY_NO
);



--■■■6순위■■■

--테이블명 
CREATE TABLE REVIEWDETAIL (
   REDETAIL_NO   NUMBER   NOT NULL,
   REVIEW_NO   NUMBER   NOT NULL,
   MSTICKER_NO   NUMBER   NOT NULL
);

ALTER TABLE REVIEWDETAIL ADD CONSTRAINT PK_REVIEWDETAIL PRIMARY KEY (
   REDETAIL_NO
);

--테이블명
ALTER TABLE ING_REPLY ADD CONSTRAINT FK_RERE_NO FOREIGN KEY(REREPLY_NO)
       REFERENCES ING_REPLY(ING_REPLY_NO);


--테이블명
CREATE TABLE REPORT_ING (
   REPORT_NO   NUMBER   NOT NULL,
   REPORTDATE   DATE   NULL,
   REPLY_NO   NUMBER   NOT NULL,
   AC_NO   NUMBER   NOT NULL,
   REASON_NO   NUMBER   NOT NULL,
   WHY   VARCHAR2(500)   NULL,
   STATUS_NO   NUMBER   NOT NULL
);

ALTER TABLE REPORT_ING ADD CONSTRAINT PK_REPORT_ING PRIMARY KEY (
   REPORT_NO
);

-- 테이블 명 바꾸기
ALTER TABLE CHECKSTICKER RENAME TO STICKER;

SELECT *
FROM STICKER;


---------------------------------------------------------------------------------------------------------------
-- 제약조건 조회 뷰 생성
CREATE OR REPLACE VIEW VIEW_CONSTCHECK
AS
SELECT UC.OWNER "OWNER"
    , UC.CONSTRAINT_NAME "CONSTRAINT_NAME"
    , UC.TABLE_NAME "TABLE_NAME"
    , UC.CONSTRAINT_TYPE "CONSTRAINT_TYPE"
    , UCC.COLUMN_NAME "COLUMN_NAME"
    , UC.SEARCH_CONDITION "SEARCH_CONDITION"
    , UC.DELETE_RULE "DELETE_RULE"
FROM USER_CONSTRAINTS UC JOIN USER_CONS_COLUMNS UCC
ON UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME;

SELECT *
FROM VIEW_CONSTCHECK;


--------------------------------------------------------------------------------------------------------------

-- 제약조건 수정(CASCADE 추가 : 북마크스티커 고유번호, 북마크 고유번호)
-- 체크리스트 부착 스티커의 기존 제약조건 삭제
/*
TEAM_SEOLO	CHECKTAG_STICKER_NO_FK	CHECKTAG	R	CSTICKER_NO		NO ACTION
TEAM_SEOLO	CHECKTAG_CH_B_NO_FK	    CHECKTAG	R	CH_B_NO		    NO ACTION
*/
ALTER TABLE CHECKTAG DROP CONSTRAINT CHECKTAG_STICKER_NO_FK;
ALTER TABLE CHECKTAG DROP CONSTRAINT CHECKTAG_CH_B_NO_FK;

-- 체크리스트 부착 스티커의 컬럼에 CASCADE 제약조건 추가
ALTER TABLE CHECKTAG ADD CONSTRAINT CHECKTAG_STICKER_NO_FK FOREIGN KEY(CSTICKER_NO)
REFERENCES STICKER(CSTICKER_NO) ON DELETE CASCADE;

ALTER TABLE CHECKTAG ADD CONSTRAINT CHECKTAG_CH_B_NO_FK FOREIGN KEY(CH_B_NO)
REFERENCES CHECK_BOOKMARK(CH_B_NO) ON DELETE CASCADE;
/*
TEAM_SEOLO	CHECKTAG_STICKER_NO_FK	CHECKTAG	R	CSTICKER_NO		CASCADE
TEAM_SEOLO	CHECKTAG_CH_B_NO_FK	    CHECKTAG	R	CH_B_NO		    CASCADE
*/

-- 지역정보 부착 스티커의 기존 제약조건 삭제
/*
TEAM_SEOLO	LOCALTAG_LO_B_NO_FK	LOCALTAG	R	LO_B_NO		NO ACTION
STICKER_NO 컬럼은 제약조건 없당...
*/
ALTER TABLE LOCALTAG DROP CONSTRAINT LOCALTAG_LO_B_NO_FK;

-- 지역정보 부착 스티커의 컬럼에 CASCADE 제약조건 추가
ALTER TABLE LOCALTAG ADD CONSTRAINT LOCALTAG_LO_B_NO_FK FOREIGN KEY(LO_B_NO)
REFERENCES LOCAL_BOOKMARK(LO_B_NO) ON DELETE CASCADE;

ALTER TABLE LOCALTAG ADD CONSTRAINT LOCALTAG_STICKER_NO_FK FOREIGN KEY(CSTICKER_NO)
REFERENCES STICKER(CSTICKER_NO) ON DELETE CASCADE;
/*
TEAM_SEOLO	LOCALTAG_STICKER_NO_FK	LOCALTAG	R	CSTICKER_NO		CASCADE
TEAM_SEOLO	LOCALTAG_LO_B_NO_FK	    LOCALTAG	R	LO_B_NO		    CASCADE
*/



-- 추가항목(시간평가), 추가항목(점수평가) 테이블의 체크리스트 고유번호 컬럼에도 CASCADE 조건 추가
/*
TEAM_SEOLO	PLUS_TIME_CHECK_NO_FK	PLUS_TIME	R	CHECK_NO		NO ACTION
TEAM_SEOLO	PLUS_SCORE_CHECK_NO_FK	PLUS_SCORE	R	CHECK_NO		NO ACTION	
*/
-- 기존 제약조건 삭제
ALTER TABLE PLUS_TIME DROP CONSTRAINT PLUS_TIME_CHECK_NO_FK;
ALTER TABLE PLUS_SCORE DROP CONSTRAINT PLUS_SCORE_CHECK_NO_FK;

-- CASCADE 제약조건 추가
ALTER TABLE PLUS_TIME ADD CONSTRAINT PLUS_TIME_CHECK_NO_FK FOREIGN KEY(CHECK_NO)
REFERENCES CHECKLIST(CHECK_NO) ON DELETE CASCADE;

ALTER TABLE PLUS_SCORE ADD CONSTRAINT PLUS_SCORE_CHECK_NO_FK FOREIGN KEY(CHECK_NO)
REFERENCES CHECKLIST(CHECK_NO) ON DELETE CASCADE;

/*
TEAM_SEOLO	PLUS_TIME_CHECK_NO_FK	PLUS_TIME	R	CHECK_NO		CASCADE
TEAM_SEOLO	PLUS_SCORE_CHECK_NO_FK	PLUS_SCORE	R	CHECK_NO		CASCADE
*/





--○ 공동구매쪽 신고 테이블들에 컬럼 추가했어요!!

-- 신고(공동구매 게시글) 테이블에 관리자 아이디와 처리일시 컬럼 추가, 제약조건 추가
ALTER TABLE REPORT_GUIN
ADD AD_ID VARCHAR2(30);

ALTER TABLE REPORT_GUIN
ADD CONFIRMDATE DATE;

ALTER TABLE REPORT_GUIN
ADD CONSTRAINT RPGUIN_AD_ID_FK FOREIGN KEY(AD_ID)
        REFERENCES ADMIN(AD_ID);
        
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'REPORT_GUIN';

-- 신고(공동구매 구인 댓글) 테이블에 관리자 아이디와 처리일시 컬럼 추가, 제약조건 추가
ALTER TABLE REPORT_GUINREPLY
ADD AD_ID VARCHAR2(30);

ALTER TABLE REPORT_GUINREPLY
ADD CONFIRMDATE DATE;

ALTER TABLE REPORT_GUINREPLY
ADD CONSTRAINT RPGUINRE_AD_ID_FK FOREIGN KEY(AD_ID)
        REFERENCES ADMIN(AD_ID);
        
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'REPORT_GUINREPLY';

        
-- 신고(공동구매 진행 댓글) 테이블에 관리자 아이디와 처리일시 컬럼 추가, 제약조건 추가
ALTER TABLE REPORT_ING
ADD AD_ID VARCHAR2(30);

ALTER TABLE REPORT_ING
ADD CONFIRMDATE DATE;

ALTER TABLE REPORT_ING
ADD CONSTRAINT RPING_AD_ID_FK FOREIGN KEY(AD_ID)
        REFERENCES ADMIN(AD_ID);
        
--------------------------------------------------------------------------------

-- 뷰
        
--○ 진하 : 신고 뷰 (이용자와 관리자가 신고 내역 볼 수 있도록)
CREATE OR REPLACE VIEW VIEW_REPORT
AS
SELECT ROWNUM AS RNUM, TITLE, STATUSNAME, REPORTDATE, REPORTER, WRITER, RPCHECK_NO, WHY
FROM
(
    SELECT W.TITLE AS TITLE, S.STATUSNAME AS STATUSNAME, R.REPORTDATE AS REPORTDATE
    , R.AC_NO AS REPORTER, C.AC_NO AS WRITER, R.RPCHECK_NO AS RPCHECK_NO, R.WHY AS WHY
    FROM REPORT_CHECK R, REPORT_WHY W, REPORT_STATUS S, CHECKLIST C
    WHERE R.WHY_NO = W.WHY_NO(+)
      AND R.STATUS_NO = S.STATUS_NO(+)
      AND R.CHECK_NO = C.CHECK_NO(+)
);
--==>> View VIEW_REPORT이(가) 생성되었습니다.
-- 뷰 순서 : 신고사유, 상태, 신고일시, 신고자(REPORTER), 원글작성자(WRITER), 신고고유번호, 상세사유

-- 신고 내역에서 확인하는 컬럼 : 순번 유형 사유 상태 날짜 시간 
-- 위에서 겹치는 거 제외하고 팝업창에서 확인하는 컬럼 : 신고자 원글작성자 신고고유번호 상세사유

-- 신고당한 곳 주소는 나중에 추가하기로 해서 안 넣었고,
-- 유형을 정하려면 어떤 신고 테이블에 의한 신고인지를 확인해야 하는데, 
-- 일단 체크리스트에 대해서만 신고를 만드는 거라서 
-- 유형에 대해서도 스킵했어

-- 커밋을 하기위한 주석 추가..
        